### PR TITLE
Vertical containers list accessibility

### PR DESCRIPTION
**Pull request by YahelCh**

### CODE REVIEW

**Comment by YahelCh** [comment]
forcing all inputs inside div with "insertValidation:false" to be bound to the vmsg span is wrong.
what if not all fields inside that group are required or have any kind of validation?
see example here:
image

**Comment by rziv** [comment]
What about checking that aria-describedby for the regular validations (not the one that are implemenred by the form) points to an existing element?

**Comment by YahelCh** [comment]
The regular validation messages are planted in a binding handler by the ko.validation engine and don't exist at this point.

**Comment by YahelCh** [comment]
How about a rule to check that inside a required-wrapper group there is at least one validation message and at list one aria-describedby that points to it?

**Comment by rziv** [comment]
Sounds good assuming there always should be such a message within the wrapper (and no cases of custom messages somewhere else)

**Comment by YahelCh** [comment]
This discussion is not related to the current pull-request.
I created new branch and added pull-request named 'requiredWrapperAccessibility'.
please see there the discussed issue, and comment/approve the current pull (verticalContainersListAccessibility).

**Comment by YahelCh** [comment]
Created new pull "use resources for messageIdPrefix".
is "Vertical containers list accessibility" approved?

**Pull request merged**
